# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mlbot_webservices.shared_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlbot', '0002_auto_20171119_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardGraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_url', models.FileField(upload_to=mlbot_webservices.shared_utils.UploadToPathAndRename('Images/User/Graphs'))),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(blank=True, max_length=256, null=True)),
                ('dashboard_url', models.FileField(blank=True, null=True, upload_to=mlbot_webservices.shared_utils.UploadToPathAndRename('Images/User/Dashboard'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='dashboardgraphs',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='mlbot.UserDashboard'),
        ),
        migrations.AddField(
            model_name='userdocs',
            name='dashboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docs_dashboard', to='mlbot.UserDashboard'),
            preserve_default=False,
        ),
    ]
