# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlbot', '0003_auto_20171127_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardgraphs',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='mlbot.UserDashboard'),
        ),
    ]
