# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlbot', '0004_auto_20171127_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdashboard',
            old_name='user',
            new_name='dashboard_user',
        ),
    ]
