# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlbot', '0005_auto_20171127_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocs',
            name='user',
        ),
    ]
