# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbot', '0006_remove_userdocs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardgraphs',
            name='graph_input_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
