# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbot', '0007_dashboardgraphs_graph_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='graph_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
