# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 08:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActualVsPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BluePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LossVsInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='predictionvalues',
            name='project',
        ),
        migrations.RemoveField(
            model_name='predictionvalues',
            name='y_yariable',
        ),
        migrations.AlterModelOptions(
            name='forecastgroupby',
            options={'verbose_name': 'Forecast group by', 'verbose_name_plural': 'Forecasts groups'},
        ),
        migrations.RemoveField(
            model_name='graph',
            name='End_time',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='Start_time',
        ),
        migrations.RemoveField(
            model_name='trainingmodel',
            name='forecast_duration',
        ),
        migrations.RemoveField(
            model_name='trainingmodel',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='trainingmodel',
            name='start_date',
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='time_yariable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_meta', to='project.Meta'),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='y_yariable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_meta', to='project.Meta'),
        ),
        migrations.DeleteModel(
            name='ForecastDuration',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.DeleteModel(
            name='PredictionValues',
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='training_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
        migrations.AddField(
            model_name='roc',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
        migrations.AddField(
            model_name='lossvsinteraction',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
        migrations.AddField(
            model_name='featureimportance',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
        migrations.AddField(
            model_name='actualvsprediction',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
    ]
