# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_dataset_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='TrainingModel',
            new_name='TrainingDetail',
        ),
        migrations.AlterField(
            model_name='accuracy',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingMetric'),
        ),
        migrations.AlterField(
            model_name='actualvsprediction',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingMetric'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingMetric'),
        ),
        migrations.AlterField(
            model_name='featureimportance',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingMetric'),
        ),
        migrations.AlterField(
            model_name='lossvsinteraction',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingMetric'),
        ),
        migrations.AlterField(
            model_name='roc',
            name='training_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingMetric'),
        ),
        migrations.AddField(
            model_name='trainingmetric',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Metric'),
        ),
    ]
