# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190101_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingMetric',
            new_name='TrainingModel',
        ),
    ]
