# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190101_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingmodel',
            old_name='training_model',
            new_name='training',
        ),
    ]
