# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190101_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='processed_data',
            new_name='data',
        ),
    ]
