# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190101_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergecolumn',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
