# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import mlbot_webservices.shared_utils


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190108_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file_url',
            field=models.FileField(upload_to=mlbot_webservices.shared_utils.UploadToPathAndRename('User/Datasets')),
        ),
    ]
