# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190109_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='imputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.MetaImputation'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.MetaRole'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.MetaType'),
        ),
    ]
