# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20190109_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdetail',
            name='forecast_group_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ForecastGroupBy'),
        ),
    ]
