# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20190112_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='mode',
            new_name='stdev',
        ),
    ]
