# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20190115_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='count',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='max',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='mean',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='min',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='missing',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
