# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-25 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import mlbot_webservices.shared_utils


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_dataset_frame_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to=mlbot_webservices.shared_utils.UploadToPathAndRename('User/Datasets')),
        ),
    ]
