# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_timetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetail',
            name='time_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.TimeType'),
        ),
    ]
