# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_trainingdetail_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetail',
            name='pipeline_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
