# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_trainingdetail_pipeline_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Metric')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingmodel',
            name='metric',
        ),
        migrations.AddField(
            model_name='modelmetric',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.TrainingModel'),
        ),
    ]
