# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mlbot_webservices.shared_utils


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_dataset_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=mlbot_webservices.shared_utils.UploadToPathAndRename('User/Training'))),
                ('frame_path', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='project.DataSet')),
            ],
        ),
    ]
