# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_trainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=37),
        ),
    ]
