# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_trainingdata_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingData',
            new_name='TestingData',
        ),
    ]
