# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-31 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_dataset_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.GraphType'),
        ),
    ]
