# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_dataset_grid_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
