# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_dataset_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetail',
            name='interupt',
            field=models.BooleanField(default=False),
        ),
    ]
