# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import mlbot_webservices.shared_utils


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_trainingdetail_interupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='csv_url',
            field=models.FileField(blank=True, null=True, upload_to=mlbot_webservices.shared_utils.UploadToPathAndRename('Images/User/Csv')),
        ),
    ]
